/**
 * Une ligne francaise par application recommandee.
 *
 * Composio decrit ses entrees en anglais, souvent sur deux ou trois phrases
 * marketing. Sur une carte, c'est illisible et ce n'est pas la langue du
 * produit. Ces libelles sont la traduction courte de leurs descriptions — pas
 * des inventions : chacun part de ce que Composio dit de l'application.
 *
 * COURT, volontairement : la carte annonce, la fenetre « Voir ce que ca fait »
 * developpe. Une phrase qui deborde casse l'alignement des cartes.
 *
 * Les vingt-trois de la vitrine ont une fiche plus riche dans `fiches.ts`, avec
 * leurs etiquettes et leurs actions ; elle passe devant celle-ci. Ce qui n'est
 * ni ici ni la-bas garde le texte anglais de Composio — c'est le fourre-tour
 * derriere « + d'integrations », que personne ne parcourt.
 */

export const DESCRIPTIONS_FR: Record<string, string> = {
	// ── Messagerie & discussion ──────────────────────────────
	gmail: 'Votre boîte Gmail.',
	outlook: 'Votre messagerie Outlook et son agenda.',
	slack: 'Vos canaux et messages Slack.',
	microsoft_teams: 'Vos conversations et canaux Teams.',
	google_chat: 'Vos espaces Google Chat.',
	discord: 'Vos serveurs et salons Discord.',
	telegram: 'Vos messages et robots Telegram.',
	whatsapp: 'WhatsApp Business, pour écrire à vos clients.',
	chatwork: 'Vos discussions d’équipe Chatwork.',
	missive: 'Vos boîtes mail partagées Missive.',
	zulip: 'Vos fils de discussion Zulip.',
	respond_io: 'Vos conversations clients, tous canaux réunis.',
	wati: 'WhatsApp pour le service client.',

	// ── Réunions ─────────────────────────────────────────────
	zoom: 'Vos réunions Zoom.',
	googlemeet: 'Vos réunions Google Meet.',
	webex: 'Vos réunions Webex.',
	clickmeeting: 'Vos webinaires ClickMeeting.',
	demio: 'Vos webinaires marketing Demio.',
	fireflies: 'Transcription et résumé de vos réunions.',
	tldv: 'Enregistrement et transcription de vos visios.',
	recallai: 'Récupère le contenu de vos réunions.',
	granola_mcp: 'Vos notes de réunion Granola.',

	// ── Agenda & rendez-vous ─────────────────────────────────
	googlecalendar: 'Votre agenda Google.',
	calendly: 'Vos pages de réservation Calendly.',
	cal: 'Vos réservations Cal.com.',
	scheduleonce: 'Prise de rendez-vous pour vos prospects.',
	supersaas: 'Réservation en ligne SuperSaaS.',
	appointo: 'Prise de rendez-vous pour boutique Shopify.',
	etermin: 'Réservation en ligne eTermin.',
	calendarhero: 'Organisation automatique de vos rendez-vous.',
	motion: 'Agenda et tâches organisés automatiquement.',
	ticktick: 'Vos tâches et listes TickTick.',
	todoist: 'Vos tâches Todoist.',
	microsoft_todo: 'Vos tâches Microsoft To Do.',

	// ── Fichiers & documents ─────────────────────────────────
	googledrive: 'Vos fichiers Google Drive.',
	one_drive: 'Vos fichiers OneDrive.',
	dropbox: 'Vos fichiers Dropbox.',
	box: 'Vos fichiers Box.',
	egnyte: 'Vos fichiers d’entreprise Egnyte.',
	share_point: 'Vos sites et documents SharePoint.',
	sharepoint_graph: 'SharePoint via Microsoft Graph.',
	googledocs: 'Vos documents Google Docs.',
	googlesheets: 'Vos tableaux Google Sheets.',
	googleslides: 'Vos présentations Google Slides.',
	onenote: 'Vos carnets OneNote.',
	notion: 'Vos pages et bases Notion.',
	coda: 'Vos documents et bases Coda.',
	excel: 'Vos classeurs Excel.',
	googlephotos: 'Vos photos Google Photos.',

	// ── CRM & ventes ─────────────────────────────────────────
	hubspot: 'Vos contacts et affaires HubSpot.',
	salesforce: 'Vos comptes et opportunités Salesforce.',
	salesforce_service_cloud: 'Le service client Salesforce.',
	pipedrive: 'Votre tunnel de vente Pipedrive.',
	attio: 'Votre CRM Attio.',
	close: 'Votre CRM de prospection Close.',
	folk: 'Vos contacts et relances Folk.',
	capsule_crm: 'Votre CRM Capsule.',
	nutshell: 'Votre CRM Nutshell.',
	zoho: 'Votre CRM Zoho.',
	zoho_bigin: 'Le CRM léger Zoho Bigin.',
	kommo: 'Votre CRM par messagerie Kommo.',
	espocrm: 'Votre CRM EspoCRM.',
	salesflare: 'Votre CRM Salesflare.',
	salesmate: 'Votre CRM Salesmate.',
	nethunt_crm: 'Le CRM NetHunt, dans Gmail.',
	highlevel: 'Votre plateforme GoHighLevel.',
	follow_up_boss: 'Le CRM immobilier Follow Up Boss.',
	forcemanager: 'Le CRM terrain ForceManager.',
	firmao: 'Votre CRM et facturation Firmao.',
	dynamics365: 'Votre CRM Microsoft Dynamics 365.',
	netsuite: 'Votre gestion NetSuite.',
	odoo: 'Votre gestion Odoo.',
	apollo: 'Recherche de prospects Apollo.',
	lusha: 'Coordonnées de prospects Lusha.',
	zoominfo: 'Données d’entreprises ZoomInfo.',
	gong: 'Analyse de vos appels commerciaux.',
	rocket_reach: 'Coordonnées professionnelles RocketReach.',
	hunter: 'Trouve les adresses mail d’une entreprise.',

	// ── Projets & tâches ─────────────────────────────────────
	asana: 'Vos projets et tâches Asana.',
	trello: 'Vos tableaux Trello.',
	monday: 'Vos tableaux Monday.com.',
	clickup: 'Vos projets ClickUp.',
	jira: 'Vos tickets Jira.',
	confluence: 'Votre base documentaire Confluence.',
	basecamp: 'Vos projets Basecamp.',
	wrike: 'Vos projets Wrike.',
	shortcut: 'Vos tickets de développement Shortcut.',
	linear: 'Vos tickets Linear.',
	teamcamp: 'Vos projets Teamcamp.',
	kanbanize: 'Vos tableaux Kanban Businessmap.',
	productboard: 'Votre feuille de route produit.',
	miro: 'Vos tableaux blancs Miro.',
	mural: 'Vos tableaux blancs Mural.',
	airtable: 'Vos bases Airtable.',
	baserow: 'Vos bases Baserow.',
	nocodb: 'Vos bases NocoDB.',
	grist: 'Vos tableaux Grist.',
	ninox: 'Vos bases Ninox.',
	fibery: 'Votre espace de travail Fibery.',

	// ── Support client ───────────────────────────────────────
	zendesk: 'Vos tickets Zendesk.',
	intercom: 'Vos conversations clients Intercom.',
	freshdesk: 'Vos tickets Freshdesk.',
	freshservice: 'Votre support informatique Freshservice.',
	help_scout: 'Vos conversations Help Scout.',
	helpdesk: 'Vos tickets HelpDesk.',
	gorgias: 'Le support client des boutiques en ligne.',
	re_amaze: 'Vos conversations Re:amaze.',
	supportbee: 'Vos tickets SupportBee.',
	plain: 'Votre support client Plain.',
	canny: 'Les retours et idées de vos clients.',
	gleap: 'Rapports de bugs et retours dans l’app.',
	servicenow: 'Vos demandes internes ServiceNow.',

	// ── Compta & paiement ────────────────────────────────────
	stripe: 'Vos paiements Stripe.',
	paypal: 'Vos paiements PayPal.',
	quickbooks: 'Votre comptabilité QuickBooks.',
	xero: 'Votre comptabilité Xero.',
	freshbooks: 'Votre facturation FreshBooks.',
	freeagent: 'Votre comptabilité FreeAgent.',
	moneybird: 'Votre facturation Moneybird.',
	sevdesk: 'Votre comptabilité sevDesk.',
	lexoffice: 'Votre comptabilité lexoffice.',
	elorus: 'Votre facturation Elorus.',
	quaderno: 'TVA et factures Quaderno.',
	square: 'Vos encaissements Square.',
	razorpay: 'Vos paiements Razorpay.',
	paystack: 'Vos paiements Paystack.',
	flutterwave: 'Vos paiements Flutterwave.',
	lemon_squeezy: 'Vos ventes Lemon Squeezy.',
	gumroad: 'Vos ventes Gumroad.',
	brex: 'Vos cartes et dépenses Brex.',
	ramp: 'Vos dépenses et notes de frais Ramp.',
	ynab: 'Votre budget YNAB.',
	taxjar: 'Vos taxes de vente TaxJar.',
	zoho_books: 'Votre comptabilité Zoho Books.',
	zoho_invoice: 'Vos factures Zoho Invoice.',
	zoho_inventory: 'Vos stocks Zoho Inventory.',

	// ── Marketing & e-mailing ────────────────────────────────
	mailchimp: 'Vos campagnes Mailchimp.',
	brevo: 'Vos campagnes Brevo.',
	sendgrid: 'Vos envois d’e-mails SendGrid.',
	mailerlite: 'Vos campagnes MailerLite.',
	mailersend: 'Vos e-mails transactionnels MailerSend.',
	klaviyo: 'Votre marketing e-commerce Klaviyo.',
	active_campaign: 'Vos scénarios marketing ActiveCampaign.',
	constant_contact: 'Vos campagnes Constant Contact.',
	omnisend: 'Vos campagnes e-commerce Omnisend.',
	moosend: 'Vos campagnes Moosend.',
	sender: 'Vos campagnes Sender.',
	emailoctopus: 'Vos campagnes EmailOctopus.',
	loops_so: 'Vos e-mails produit Loops.',
	customerio: 'Vos messages automatisés Customer.io.',
	iterable: 'Vos campagnes multicanales Iterable.',
	postmark: 'Vos e-mails transactionnels Postmark.',
	resend: 'Vos e-mails transactionnels Resend.',
	mailtrap: 'Vos tests et envois d’e-mails Mailtrap.',
	kit: 'Votre newsletter Kit.',
	instantly: 'Vos campagnes de prospection Instantly.',
	lemlist: 'Vos campagnes de prospection Lemlist.',
	reply_io: 'Vos séquences de prospection Reply.io.',
	woodpecker_co: 'Vos relances commerciales Woodpecker.',
	ayrshare: 'Publication sur tous vos réseaux.',
	postiz_mcp: 'Planification de vos publications Postiz.',
	typefully: 'Rédaction et planification de vos posts.',
	planly: 'Planification de vos réseaux sociaux.',
	metaads: 'Vos publicités Facebook et Instagram.',
	linkedin_ads: 'Vos publicités LinkedIn.',
	googleads: 'Vos publicités Google Ads.',

	// ── Réseaux sociaux ──────────────────────────────────────
	linkedin: 'Votre présence LinkedIn.',
	facebook: 'Votre page Facebook.',
	twitter: 'Votre compte X.',
	instagram: 'Votre compte Instagram.',
	tiktok: 'Votre compte TikTok.',
	youtube: 'Votre chaîne YouTube.',
	reddit: 'Vos publications Reddit.',
	snapchat: 'Votre compte Snapchat.',

	// ── RH & temps ───────────────────────────────────────────
	bamboohr: 'Vos salariés et congés BambooHR.',
	gusto: 'Votre paie Gusto.',
	workday: 'Vos RH et paie Workday.',
	sap_successfactors: 'Vos RH SAP SuccessFactors.',
	greenhouse: 'Vos recrutements Greenhouse.',
	lever: 'Vos recrutements Lever.',
	ashby: 'Vos recrutements Ashby.',
	recruitee: 'Vos recrutements Recruitee.',
	workable: 'Vos recrutements Workable.',
	breezy_hr: 'Vos recrutements Breezy HR.',
	breathehr: 'Vos RH Breathe.',
	talenthr: 'Vos RH TalentHR.',
	connecteam: 'Vos équipes de terrain Connecteam.',
	timecamp: 'Votre suivi du temps TimeCamp.',
	clockify: 'Votre suivi du temps Clockify.',
	toggl: 'Votre suivi du temps Toggl.',
	harvest: 'Temps passé et facturation Harvest.',
	everhour: 'Votre suivi du temps Everhour.',
	timely: 'Votre suivi du temps Timely.',

	// ── Signature & devis ────────────────────────────────────
	docusign: 'Vos signatures électroniques DocuSign.',
	dropbox_sign: 'Vos signatures Dropbox Sign.',
	pandadoc: 'Vos devis et contrats PandaDoc.',
	documenso: 'Vos signatures Documenso.',
	docuseal: 'Vos signatures DocuSeal.',
	signwell: 'Vos signatures SignWell.',
	signaturely: 'Vos signatures Signaturely.',
	eversign: 'Vos signatures eversign.',
	esignatures_io: 'Vos contrats signés en ligne.',
	boldsign: 'Vos signatures BoldSign.',
	better_proposals: 'Vos propositions commerciales.',

	// ── Vente en ligne & livraison ───────────────────────────
	shopify: 'Votre boutique Shopify.',
	wix: 'Votre site Wix.',
	webflow: 'Votre site Webflow.',
	loyverse: 'Votre caisse Loyverse.',
	baselinker: 'Vos commandes multi-boutiques BaseLinker.',
	cloudcart: 'Votre boutique CloudCart.',
	shippo: 'Vos expéditions Shippo.',
	shipengine: 'Vos expéditions ShipEngine.',
	shipday: 'Vos livraisons Shipday.',
	detrack: 'Le suivi de vos livraisons Detrack.',
	route4me: 'Vos tournées de livraison Route4Me.',
	optimoroute: 'Vos tournées optimisées OptimoRoute.',
	payhip: 'Vos ventes de produits numériques.',
	whop: 'Vos abonnements et ventes Whop.',

	// ── Formulaires & enquêtes ───────────────────────────────
	typeform: 'Vos formulaires Typeform.',
	jotform: 'Vos formulaires Jotform.',
	tally: 'Vos formulaires Tally.',
	fillout_forms: 'Vos formulaires Fillout.',
	formbricks: 'Vos enquêtes Formbricks.',
	getform: 'Les réponses de vos formulaires Getform.',
	formsite: 'Vos formulaires Formsite.',
	paperform: 'Vos formulaires Paperform.',
	survey_monkey: 'Vos enquêtes SurveyMonkey.',
	googleforms: 'Vos formulaires Google Forms.',
	delighted: 'La satisfaction de vos clients Delighted.',
	satismeter: 'La satisfaction de vos clients SatisMeter.',
	refiner: 'Vos enquêtes clients Refiner.',
	simplesat: 'La satisfaction après support.',
	retently: 'Votre score de recommandation client.',

	// ── Analyse & données ────────────────────────────────────
	google_analytics: 'La fréquentation de votre site.',
	microsoft_power_bi: 'Vos tableaux de bord Power BI.',
	metabase: 'Vos tableaux de bord Metabase.',
	mixpanel: 'L’usage de votre produit Mixpanel.',
	amplitude: 'L’usage de votre produit Amplitude.',
	posthog: 'L’usage de votre produit PostHog.',
	plausible_analytics: 'La fréquentation de votre site Plausible.',
	simple_analytics: 'La fréquentation de votre site.',
	databox: 'Vos indicateurs Databox.',
	klipfolio: 'Vos tableaux de bord Klipfolio.',
	google_search_console: 'Votre présence dans Google.',
	semrush: 'Votre référencement Semrush.',
	ahrefs: 'Votre référencement Ahrefs.',
	moz: 'Votre référencement Moz.',

	// ── Automatisation ───────────────────────────────────────
	make: 'Vos scénarios automatisés Make.',
	bubble: 'Votre application Bubble.',
	softr: 'Votre application Softr.',
	nango: 'Vos connexions applicatives Nango.',
	celigo: 'Vos flux entre logiciels Celigo.',

	// ── Recherche & extraction web ───────────────────────────
	exa: 'Recherche web pensée pour l’IA.',
	tavily: 'Recherche web pour l’assistant.',
	firecrawl: 'Lit un site entier et le met en texte.',
	perplexityai: 'Réponses sourcées Perplexity.',
	linkup: 'Recherche web Linkup.',
	openperplex: 'Recherche web Openperplex.',
	serpapi: 'Les résultats Google, exploitables.',
	brightdata: 'Extraction de données web Bright Data.',
	apify: 'Vos robots d’extraction Apify.',
	browseai: 'Surveille une page et en extrait les données.',
	browserbase_tool: 'Un navigateur piloté par l’assistant.',
	hyperbrowser: 'Un navigateur piloté par l’assistant.',
	scrapegraph_ai: 'Extraction de pages web par l’IA.',
	diffbot: 'Transforme une page web en données.',
	agentql: 'Interroge une page web comme une base.',
	kadoa: 'Extraction de données web Kadoa.',
	news_api: 'L’actualité de la presse mondiale.',
	composio_search: 'La recherche web de Composio.',

	// ── Mémoire & bases vectorielles ─────────────────────────
	mem0: 'Donne une mémoire longue à l’assistant.',
	zep: 'Mémoire de conversation Zep.',
	pinecone: 'Votre base vectorielle Pinecone.',
	ragie: 'Vos documents, interrogeables par l’IA.',
	needle: 'Vos documents, interrogeables par l’IA.',

	// ── Bac à sable de code ──────────────────────────────────
	e2b: 'Exécute du code en sécurité.',
	daytona: 'Environnements de développement isolés.',

	// ── Développement & design ───────────────────────────────
	github: 'Vos dépôts GitHub.',
	gitlab: 'Vos dépôts GitLab.',
	bitbucket: 'Vos dépôts Bitbucket.',
	gitea: 'Vos dépôts Gitea.',
	sentry: 'Les erreurs de vos applications.',
	datadog: 'La surveillance de vos serveurs Datadog.',
	new_relic: 'La surveillance de vos applications.',
	grafana: 'Vos tableaux de bord Grafana.',
	pagerduty: 'Vos alertes et astreintes PagerDuty.',
	incident_io: 'La gestion de vos incidents.',
	rootly: 'La gestion de vos incidents Rootly.',
	circleci: 'Vos chaînes de build CircleCI.',
	buildkite: 'Vos chaînes de build Buildkite.',
	vercel: 'Vos déploiements Vercel.',
	render: 'Vos déploiements Render.',
	railway: 'Vos déploiements Railway.',
	fly: 'Vos déploiements Fly.io.',
	digital_ocean: 'Vos serveurs DigitalOcean.',
	cloudflare: 'Vos domaines et sécurité Cloudflare.',
	supabase: 'Votre base de données Supabase.',
	neon: 'Votre base PostgreSQL Neon.',
	snowflake: 'Votre entrepôt de données Snowflake.',
	databricks: 'Votre plateforme de données Databricks.',
	elasticsearch: 'Votre moteur de recherche Elasticsearch.',
	postman: 'Vos API Postman.',
	figma: 'Vos maquettes Figma.',
	penpot: 'Vos maquettes Penpot.',
	zeplin: 'Vos maquettes remises aux développeurs.',
	sourcegraph: 'La recherche dans votre code.',
	npm: 'Les paquets npm.',
	docker_hub: 'Vos images Docker.',

	// ── Modèles IA ───────────────────────────────────────────
	openai: 'Les modèles OpenAI.',
	gemini: 'Les modèles Gemini de Google.',
	mistral_ai: 'Les modèles Mistral.',
	deepseek: 'Les modèles DeepSeek.',
	hugging_face: 'Les modèles Hugging Face.',
	elevenlabs: 'Voix de synthèse ElevenLabs.',
	replicate: 'Modèles d’image et de son Replicate.',
	openrouter: 'Des dizaines de modèles, une seule clé.',
	ollama: 'Vos modèles Ollama, en local.',
	wolfram_alpha_api: 'Calcul et savoir scientifique.'
};

/** Libelle francais d'une application, ou null si elle n'en a pas. */
export const descriptionFr = (slug: string): string | null =>
	DESCRIPTIONS_FR[`${slug}`.toLowerCase()] ?? null;
